### ISSUE TITLE
Credentials in /config/dev.js

### ISSUE THREAD

**Issue by ketus** [jehunter5811/react-auth-crud-boilerplate#1]
There are credentials and tokens commited in react-auth-crud-boilerplate/config/dev.js

I advise to swap them to Node environment variables.

**Comment by polluterofminds** [comment]
@ketus Thanks so much! That had previously been part of the gitignore file...not sure what happened. I appreciate the heads up!

**Comment by ketus** [comment]
Well, sh.... things happen :) If you used those tokens elsewhere you 'd want to regenerate them, I think :) all the best.
